[package]
name = "pallas"
version = "0.1.0"
edition = "2021"

[dependencies]
hemtt-pbo = { git = "https://github.com/brettmayson/hemtt" }
hemtt-signing = { git = "https://github.com/brettmayson/hemtt" }

dashmap = "6.1.0"
indicatif = "0.17.9"
rayon = "1.10.0"
savefile = "0.18.5"
savefile-derive = "0.18.5"
clap = { version = "4.5.23", features = ["derive"] }
anyhow = "1.0.95"
